# Site settings
title: Suo Qiu's pages
email: q.suo@foxmail.com
description: Personal Site
baseurl:
url:
twitter_username:
github_username:  kyuusaku

# Build settings
markdown: kramdown
permalink: pretty
